app_name = "crgo"
app_env = "local"
debug = true
jwt_key = "33446a9dcf9ea060a0a6532b166da32f304af0de"
timezone = "Asia/Shanghai"
http_addr = "127.0.0.1"
http_port = 8001
http_connect = "127.0.0.1:8001"
grpc_addr =  "127.0.0.1"
grpc_port =  "8081"
grpc_connect = "127.0.0.1:8081"
consul_addr = "127.0.0.1"
consul_port = 8500
consul_on = false


# 日志
LOG_TYPE = "daily"
LOG_LEVEL= "debug"


# 流控资源明
sentinel_flow_resource = "request"
sentinel_flow_Threshold = 5000            # 每秒限制请求数
sentinel_stat_interval_in_ms = 1000            # 计算间隔 ms数



[database]
[database.default]
dsn = "root:@tcp(127.0.0.1:3306)/test?parseTime=true&charset=utf8&loc=Asia%2FShanghai"
max_open_conns = 30
mac_idle_conns = 10
max_life_seconds = 300
debug = true



[redis]
[redis.default]
addr = "127.0.0.1:6379"
db = 0
password = ""

[redis.session]
addr = "127.0.0.1:6379"
db = 1
password = ""


[cdn]
domain = ""


[rabbitmq]
[rabbitmq.test]
dsn = "amqp://guest:guest@127.0.0.1:5672/"


[blacklist]
    filePath = "./blacklist.txt"